when:
  - event: ["push", "manual"]
    branch: ["main", "dev"]
  - event: ["pull_request"]
    branch: ["dev"]

engine: "nixery"

clone:
  skip: false
  depth: 1
  submodules: false

dependencies:
  nixpkgs:
    - bash
    - coreutils
    - curl
    - exiftool
    - file
    - git
    - gnugrep
    - gnused
    - hostname
    - jq
    - mediainfo
    - shellcheck

environment:
  ATFILE_DEBUG: "0"
  ATFILE_DEVEL_ENABLE_PUBLISH: "0"

steps:
  - name: "Print system files"
    command: "find / -path /proc -prune -o -path /dev -prune -o -path /sys -prune -o -path /run -prune -o -print"
  - name: "Debug"
    command: "./atfile.sh something-broke"
  - name: "Build"
    command: "./atfile.sh build"
